server:
  port: 8081
spring:
  profiles:
    active: native
  application:
    name: STUDENT
  devtools:
    livereload:
      enabled: true
    add-properties: false
  datasource:
    url: jdbc:mysql://db-student.caoaqarffybx.us-east-1.rds.amazonaws.com:3306/service-student?useUnicode=true&characterEncoding=utf8
    username: admin
    password: ENC(ykEmwI79pjVHJ86lKl9/x25i1wNbJXBT)
    #url: jdbc:mysql://localhost:3306/academic_system?useUnicode=true&characterEncoding=utf8
    #username: root
    #password: ENC(5quOixJemPFM0CMX/ylGyPf6gm5TqFv+)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 600000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        '[format_sql]': true
        '[use_sql_comments]': true
        '[order_insert]': true
        '[order_updates]': true
        '[generate_statistics]': true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost
jasypt:
  encryptor:
    password: secret
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  file:
    name: logs/student.log
    max-size: 10MB
    max-history: 365
  level:
    root: INFO
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
management:
  endpoints:
    web:
      base-path: /act
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
